[colors.primary]
background = "#141414"
foreground = "#ffffff"

[colors.normal]
black = "#1c1c1c"
red = "#da5858"
green = "#3fc661"
yellow = "#e8ca5e"
blue = "#497ee9"
magenta = "#d56cc3"
cyan = "#5cd8e6"
white = "#ffffff"

[colors.bright]
black = "#222222"
red = "#e36d6d"
green = "#61d67e"
yellow = "#fadd75"
blue = "#5d8dee"
magenta = "#df81cf"
cyan = "#7eeaf6"
white = "#e0e0e1"
