[colors.primary]
background = "#061115"
foreground = "#D9D7D6"

[colors.normal]
black = "#232526"
red = "#DF5B61"
green = "#78B892"
yellow = "#de8f78"
blue = "#6791c9"
magenta = "#bc83e3"
cyan = "#67AFC1"
white = "#e4e6e7"

[colors.bright]
black = "#2c2e2f"
red = "#e8646a"
green = "#81c19b"
yellow = "#e79881"
blue = "#709ad2"
magenta = "#c58cec"
cyan = "#70b8ca"
white = "#f2f4f5"
