[colors.primary]
background = "#fafafa"
foreground = "#54555b"

[colors.normal]
black = "#EAEAEB"
red = "#DF5B61"
green = "#78B892"
yellow = "#de8f78"
blue = "#6791c9"
magenta = "#bc83e3"
cyan = "#67AFC1"
white = "#54555b"

[colors.bright]
black = "#EAEAEB"
red = "#e8646a"
green = "#81c19b"
yellow = "#e79881"
blue = "#709ad2"
magenta = "#c58cec"
cyan = "#70b8ca"
white = "#54555b"
