import = [ '~/.config/alacritty/colors/dark.toml' ]

[font]
size = 13.5
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "Bold" }
italic = { family = "Liga SFMono Nerd Font", style = "Italic" }
bold_italic = { family = "Liga SFMono Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 6 }
glyph_offset = { x = 0, y = 4 }

[window]
decorations = "full"
opacity = 1
title = "Terminal"
dynamic_title = true
resize_increments = true
padding = { x = 40, y = 40 }

[selection]
save_to_clipboard = false

[cursor]
unfocused_hollow = false
blink_interval = 550
style = { shape = "Beam", blinking = "Always" }
