import = [ '~/.config/alacritty/colors/one_light.toml' ]

[font]
size = 15

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 8

[font.glyph_offset]
x = 0
y = 4

[window.padding]
x = 40
y = 40

[window]
decorations = "full"
opacity = 1
dynamic_title = true

[selection]
save_to_clipboard = false

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor]
unfocused_hollow = false
blink_interval = 550
