general.import = [ '~/.config/alacritty/colors/dark.toml' ]

[font]
size = 12.5
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "Bold" }
italic = { family = "Liga SFMono Nerd Font", style = "Italic" }
bold_italic = { family = "Liga SFMono Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 6 }
glyph_offset = { x = 0, y = 4 }

[window]
opacity = 1
title = "sowntee@dev"
padding = { x = 30, y = 30 }

[cursor]
blink_interval = 1000
style = { shape = "Beam", blinking = "Always" }
