live_config_reload = true

[window.padding]
x = 30
y = 30

[window]
decorations = "full"
opacity = 1.0
dynamic_title = true

[selection]
save_to_clipboard = false

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor]
unfocused_hollow = false
blink_interval = 550
